# ===============================
# Configuración de la base de datos
# ===============================
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=TurnosJava;encrypt=false;trustServerCertificate=true
spring.datasource.username=Cebo
spring.datasource.password=Ag555293

spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ===============================
# Configuración de JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect






